### ISSUE TITLE
agetty autologin

### ISSUE THREAD

**Issue by mrgreenlinux** [artix-linux/system#11]
I use agetty to autologin to console.

c1:12345:respawn:/usr/bin/agetty 38400 tty1 linux
c2:2345:respawn:/usr/bin/agetty 38400 tty2 linux
c3:2345:respawn:/usr/bin/agetty 38400 tty3 linux
c4:2345:respawn:/usr/bin/agetty 38400 tty4 linux
c5:2345:respawn:/usr/bin/agetty 38400 tty5 linux
#c6:2345:respawn:/usr/bin/agetty 38400 tty6 linux
c6:2345:respawn:/usr/bin/agetty - ablive --noclear 38400 tty6 linux

Worked with old openrc version now I get login prompt, does artix still use inittab?

**Comment by cromerc** [comment]
No, artix does not have sysvinit. It uses openrc-init. So naturally inittab is not used.

The options for agetty can be configured in /etc/conf.d/agetty.tty*

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mrgreenlinux** [comment]
Thanks Chris.... ;)
