### ISSUE TITLE
Conky sur artix linux [FR]

### ISSUE THREAD

**Issue by LinuxVieLoisir** [artix-linux/system#18]
Bonjour, j'ai installer artix linux recemment, mais je ne parviens pas à utiliser conky. Je l'ai installer, mais quand je le lance en ligne de commande je recois l'erreur :  "conky: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory"

Pour information j'utilise le bureau lxqt, celui que vous nous conseillez.

Je vous remercie par avance dans l'attente de votre réponse, bien cordialement.

**Comment by cromerc** [comment]
I don't speak french. But:
sudo pacman -S systemd-dummy libsystemd-dummy

_Sent from my Motorola Moto G (4) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LinuxVieLoisir** [comment]
I did what you said me and I have a new error : "conky: missing text block in configuration"
Could you help me please, I search of my side too.

**Comment by cromerc** [comment]
Now you have a different problem. Your .conkyrc file is not setup correctly. Here it talks about some fixes: https://ubuntuforums.org/showthread.php?t=924857

**Comment by cromerc** [comment]
Going to close this issue. If you need any other help feel free to reopen this issue or start a new one.
