### ISSUE TITLE
GCC conflicts with GCC-multilib

### ISSUE THREAD

**Issue by ibrokemypie** [artix-linux/system#24]
When following http://systemd-free.org/news.php I was faced with ``:: gcc-multilib: removing gcc-libs-multilib breaks dependency 'gcc-libs-multilib=7.1.1-4'``
I was able to overcome this by adding ``--ignore gcc --ignore gcc-libs`` to the end of the ``pacman -Su base base-devel`` command, but that was a less than optimal experience.

**Comment by archnous** [comment]
This is normal, gcc must conflict with gcc-multilib. Also, in the guide it is repeatedly stated it is intended for knowledgeable users. Having to add an --ignore argument to circumvent a pacman warning is hardly making it a "less than optimal experience".
