### ISSUE TITLE
manjaro-keyring

### ISSUE THREAD

**Issue by physkets** [artix-linux/system#25]
Can the *manjaro-keyring* also be added to the the [system] repository? This would make retention of  Manjaro's [extra] and [community], a valid possibility.

**Comment by udeved** [comment]
Nope, since this would only work properly on unstable manjaro branch.

**Comment by thefallenrat** [comment]
Well, you can add manjaro's `[core]` repo below artix ones so that you can keep `manjaro-keyring` and such....
