### ISSUE TITLE
buildbot

### ISSUE THREAD

**Issue by udeved** [artix-linux/system#3]
@aadityabagga 

After moving to artix org, what's the status of the buildbot?

**Comment by aadityabagga** [comment]
Hi @udeved,

I'll try to look at it today.

**Comment by aadityabagga** [comment]
@udeved 

which bootstrap approach should we take?

* bootstrap via packages like https://github.com/tokland/arch-bootstrap/blob/master/arch-bootstrap.sh
* or bootstrap via iso like https://github.com/mikkeloscar/arch-travis/blob/master/arch-travis.sh

**Comment by udeved** [comment]
@aadityabagga 

I guess it depends what is better in terms of caching the bootstrap packages?
With iso, we would have to regularly provide an iso every month or so, and I would prbably prefer the repo bootstrap. However, I think repo has more disadvantages?
I guess take what works best and most effectively.
The arch bootstrap stated, it takes additional 3 minutes.

**Comment by aadityabagga** [comment]
ah, ok. will try the packages one first then since that was what is being used currently.

i tried yesterday but pacman seems to not find the repo..

* https://travis-ci.org/aadityabagga/system/builds/256515859
* https://github.com/aadityabagga/system/commits/travis

**Comment by udeved** [comment]
@aadityabagga 

I believe I have spotted the error in the bootstrap script.

artix repo url is same as on arch.

`some_url/$repo/os/$arch`

I think the **os** dir is missing.

**Comment by aadityabagga** [comment]
Had added the os dir in the base repo url itself, changed that.

I see the real issue now: the script first uses curl to fetch the html from the repo url and then extracts package links from it; in this case its fetching the page from sourceforge which contains lots of links other than the package links and hence it fails..

https://travis-ci.org/aadityabagga/system/builds/258842258#L111

**Comment by udeved** [comment]
@aadityabagga 

News, great news.
we got an artix 12 core vserver up and running.
Timelimit is no more. We just need to decide what software we gonna use on the server.

**Comment by aadityabagga** [comment]
Thats cool! 🙂 

I have experience with [Gitlab CI](https://docs.gitlab.com/runner/), its pretty nice and similar to Travis, but it would require hosting on gitlab.com rather than github.com.

An option is [buildbot](https://buildbot.net/), we could try that as it seems standalone. Its [being used](https://build.voidlinux.eu/) at used at VoidLinux afaik.

Another option is [jenkins](https://jenkins.io/solutions/github/) which seems simpler to setup and more documented, but it runs on and requires Java.

**Comment by udeved** [comment]
I just had some read on CI systems.
I figured jenkins is the most flexible, and tons of plugins, among them github plugin.
So we'd have the option any time to host git differently.

**Comment by aadityabagga** [comment]
Ok. If I can assist in installation or setting it up let me know.

**Comment by udeved** [comment]
@aadityabagga 

Just talk to nous on irc, we got it setup, just needs some more fine tuning. ;)
