### ISSUE TITLE
valgrind and lib32-glibc can't be updated

### ISSUE THREAD

**Issue by h4tr3d** [artix-linux/system#36]
valgrind and lib32-glibc requires glibc>=2.26. But system repo provides only 2.25

**Comment by thefallenrat** [comment]
Enable `[system-testing]` in `/etc/pacman.conf`

Also read this : 

https://artixlinux.org/forum/index.php/topic,27.0.html

**Comment by h4tr3d** [comment]
@thefallenrat primary repo was updated already. But I am not ready to enable `xxx-testing` repos ;-) Or is this the only way?

**Comment by thefallenrat** [comment]
> Or is this the only way?

Yes
