### ISSUE TITLE
[testing] [pacman] [icu] need rebuild 

### ISSUE THREAD

**Issue by alium** [artix-linux/system#48]
after update from [testing] pacman-5.0.2-9 works no more, because is rebuild against wrong ICU:

pacman: error while loading shared libraries: libicuuc.so.59: cannot open shared object file: No such file or directory

In testing are now icu-60.1, not icu-59.x !!!

**Comment by alium** [comment]
curl works not too:
/usr/bin/curl: error while loading shared libraries: libicuuc.so.59: cannot open shared object file: No such file or directory

**Comment by thefallenrat** [comment]
> after update from [testing] pacman-5.0.2-9 works no more, because is rebuild against wrong ICU

Clearly not : 

```
~ >>> pacman -Q pacman                                                                                                                                                   
pacman 5.0.2-9
~ >>> pacman -Q icu                                                                                                                                                      
icu 60.1-1
```

> In testing are now icu-60.1, not icu-59.x !!!

We know, that's why we bump the pacman in first place !!!

https://github.com/artix-linux/system/commit/06d1063d017bab865c55b174b04befa0cecfb8a3

**Comment by alium** [comment]
artix's downloaded package after update today:
boost-libs-1.65.1-2-x86_64.pkg.tar.xz
boost-1.65.1-2-x86_64.pkg.tar.xz
cmake-3.9.5-1-x86_64.pkg.tar.xz
cryptsetup-1.7.5-2-x86_64.pkg.tar.xz
cups-filters-1.17.9-3-x86_64.pkg.tar.xz
cups-2.2.6-1-x86_64.pkg.tar.xz
dbus-1.12.0-1-x86_64.pkg.tar.xz
device-mapper-2.02.176-1-x86_64.pkg.tar.xz
expat-2.2.5-1-x86_64.pkg.tar.xz
filesystem-2017.11-1-x86_64.pkg.tar.xz
glib2-2.54.2-2-x86_64.pkg.tar.xz
gnupg-2.2.2-1-x86_64.pkg.tar.xz
gtk-update-icon-cache-3.22.26-1-x86_64.pkg.tar.xz
gtk3-print-backends-3.22.26-1-x86_64.pkg.tar.xz
gtk3-3.22.26-1-x86_64.pkg.tar.xz
harfbuzz-icu-1.7.0-1-x86_64.pkg.tar.xz
harfbuzz-1.7.0-1-x86_64.pkg.tar.xz
hicolor-icon-theme-0.17-1-any.pkg.tar.xz
icu-60.1-1-x86_64.pkg.tar.xz
imagemagick-6.9.9.23-1-x86_64.pkg.tar.xz
iproute2-4.14.1-2-x86_64.pkg.tar.xz
libblockdev-2.12-1.1-x86_64.pkg.tar.xz
libcups-2.2.6-1-x86_64.pkg.tar.xz
libdrm-2.4.88-1-x86_64.pkg.tar.xz
libglvnd-1.0.0-1-x86_64.pkg.tar.xz
libic
libnghttp2-1.27.0-1-x86_64.pkg.tar.xz
libnm-glib-1.10.0-1-x86_64.pkg.tar.xz
libnm-1.10.0-1-x86_64.pkg.tar.xz
libplist-2.0.0+11+gec9ba8b-1-x86_64.pkg.tar.xz
libpulse-11.1-1.1-x86_64.pkg.tar.xz
libqalculate-2.1.0-2-x86_64.pkg.tar.xz
libthai-0.1.27-1.1-x86_64.pkg.tar.xz
libuv-1.16.1-1-x86_64.pkg.tar.xz
libva-mesa-driver-17.2.5-1-x86_64.pkg.tar.xz
libwacom-0.26-1-x86_64.pkg.tar.xz
libxau-1.0.8-2.1-x86_64.pkg.tar.xz
libxcb-1.12-1.1-x86_64.pkg.tar.xz
libxdmcp-1.1.2-1.1-x86_64.pkg.tar.xz
libxml2-2.9.7+4+g72182550-2-x86_64.pkg.tar.xz
libxslt-1.1.32+3+g32c88216-1-x86_64.pkg.tar.xz
lvm2-2.02.176-1-x86_64.pkg.tar.xz
mesa-17.2.5-1-x86_64.pkg.tar.xz
networkmanager-1.10.0-1-x86_64.pkg.tar.xz
openrc-0.34.6-1-x86_64.pkg.tar.xz
openssl-1.1.0.g-1-x86_64.pkg.tar.xz
pacman-5.0.2-9-x86_64.pkg.tar.xz
poppler-glib-0.61.1-1-x86_64.pkg.tar.xz
poppler-qt5-0.61.1-1-x86_64.pkg.tar.xz
poppler-0.61.1-1-x86_64.pkg.tar.xz
pulseaudio-bluetooth-11.1-1.1-x86_64.pkg.tar.xz
pulseaudio-gconf-11.1-1.1-x86_64.pkg.tar.xz
pulseaudio-11.1-1.1-x86_64.pkg.tar.xz
python-setuptools-1:36.7.1-1-any.pkg.tar.xz
qt5-base-5.9.2-2-x86_64.pkg.tar.xz
qt5-declarative-5.9.2-2-x86_64.pkg.tar.xz
qt5-location-5.9.2-2-x86_64.pkg.tar.xz
qt5-webkit-5.212.0alpha2-8-x86_64.pkg.tar.xz
syslog-ng-3.12.1-3-x86_64.pkg.tar.xz
thin-provisioning-tools-0.7.5-1-x86_64.pkg.tar.xz
tslib-1.14-1-x86_64.pkg.tar.xz
usbmuxd-1.1.0+28+g46bdf3e-1-x86_64.pkg.tar.xz
vulkan-intel-17.2.5-1-x86_64.pkg.tar.xz
xcb-proto-1.12-3.1-any.pkg.tar.xz
xcb-util-image-0.4.0-1.1-x86_64.pkg.tar.xz
xcb-util-keysyms-0.4.0-1.1-x86_64.pkg.tar.xz
xcb-util-renderutil-0.3.9-1.1-x86_64.pkg.tar.xz
xcb-util-wm-0.4.1-1.1-x86_64.pkg.tar.xz
xcb-util-0.4.0-1.1-x86_64.pkg.tar.xz
xf86-video-intel-1:2.99.917+800+g37a682aa-1-x86_64.pkg.tar.xz
xproto-7.0.31-1.1-any.pkg.tar.xz

(need restart?)

**Comment by alium** [comment]
> We know, that's why we bump the pacman in first place !!!

of course, i dont thik, that your guys are idiots :-D :-D

But for me not works...

**Comment by thefallenrat** [comment]
> (need restart?)

restart won't help anything since you borked pacman. If you have older version of icu in your cache, you may extract them into your root (`/`), and downgrade all of the packages from previous update.

If I were to take guess, the problem maybe lies in you did not update `libpsl` package. I assume because it couldn't install `libidn2`, correct? If it does, you need to install both of those as they are need by a new version pacman. To do that you need to enable arch's `[core]` repo, then install those or you can wait until someone introduced it into `[system-testing]`

**Comment by alium** [comment]
> I assume because it couldn't install libidn2, correct?
Correct!

I downgraded completly today's update, after fix the pacman.
 
You right! problem was in missing libidn2. Thanks for help, no bug, but blindsideing... :-)
