### ISSUE TITLE
rankmirrors

### ISSUE THREAD

**Issue by archnous** [artix-linux/system#51]
It won't work on our repos, because it ranks by pulling core.db; we can either put a sed in PKGBUILD to replace core.db with system.db (simple) or modify it to use either (far more troublesome). I say we use the former, to ease the load on mirror1, because as it is people rarely pull from the other mirrors. Opinions?

`sed -i 's/core/system/g' /usr/bin/rankmirrors`

**Comment by thefallenrat** [comment]
Agree with the former. Less modifications from upstream

>

**Comment by udeved** [comment]
We should patch pacman source, the rankmirrors script, since we build pacman anyway. :)

**Comment by archnous** [comment]
Yup, that sed was meant to be put inside the PKGBUILD.

**Comment by udeved** [comment]
I had the idea of creating a patch instead of the sed.

Btw, we still need webengine in testing so we can move to stable asap.
