### ISSUE TITLE
[build-fail] gpm

### ISSUE THREAD

**Issue by udeved** [artix-linux/system#56]
https://bugzilla.redhat.com/show_bug.cgi?id=1500092

@thefallenrat 

;)

**Comment by udeved** [comment]
https://src.fedoraproject.org/rpms/gpm/pull-request/1#request_diff

**Comment by thefallenrat** [comment]
hehe thanks! :D

**Comment by thefallenrat** [comment]
should've fixed now with : https://github.com/artix-linux/system/commit/e54704a64bae8a564a6ad60a9f0676e1c44e199e
