### ISSUE TITLE
Should we have an /etc/os-release symlink?

### ISSUE THREAD

**Issue by physkets** [artix-linux/system#60]
This seems to be a standard (albeit one forced by systemd) amongst other distros. Should we adopt it too? Are there any reasons not to?

The file seems to be a symlink to `/usr/lib/os-release`, which we already have.

* https://git.archlinux.org/svntogit/packages.git/commit/?id=f774b36fd4ab7a48c0fd5eeaa53c98ab3ead7498
* http://0pointer.de/blog/projects/os-release.html

The advantage is that is will increase our distro's compatibility with applications that use it for identifying the distro.

**Comment by thefallenrat** [comment]
Fixed with b5bc692

Closing .....

**Comment by physkets** [comment]
In the Arch commit I linked to, what exactly does the `systemd-tmpfiles --create etc.conf` do?

**Comment by thefallenrat** [comment]
Look at the line above the command in the commit you linked

**Comment by physkets** [comment]
Okay, so then why aren't we using that? (since we have `opentmpfiles`) And how is it different from the symlink that you put?

**Comment by thefallenrat** [comment]
I rather do this in a package that already provides `/usr/lib/os-release` than in another package where as far as I know only openRC users that benefit this

So no
