### ISSUE TITLE
linux-lts jumped into the 4.14.x series

### ISSUE THREAD

**Issue by graysky2** [artix-linux/system#70]
Are you guys planning to jump as well or stay with the 4.9.x series?

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux-lts&id=aaf1e2211feaefac7acab86b94ca80de381c543d

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux-lts&id=d9eb6c8046bcd2265f6bb6e2a777f4752a7ebc2f

**Comment by udeved** [comment]
I think we go with lts 4.14.

@graysky2 

Did you notice the message regarding our git repo switch?

**Comment by graysky2** [comment]
@udeved - No, where was that posted?

**Comment by udeved** [comment]
https://github.com/artix-linux/artools/issues/38

And the new repos here:

We just haven't decided when we switch it. I still have to test out moving packages properly, we gonna follow arch structure, which enables us to move packages individually. However, its more responsibility on maintainer side.

* [packages](https://github.com/artix-linux/packages) repo
    * system
    * world

* [packages-galaxy](https://github.com/artix-linux/packages-galaxy) repo
    * galaxy 
    * lib32

The jenkinsfile pipeline will translate arch repo names into artix repo names, so we use arch repo names.

The translation schema in the pipeline:

* staging->goblins
* testing->gremlins
* core->system
* extra->world
* community->galaxy
* multilib->lib32

**Comment by graysky2** [comment]
Just let me know when and what to do.  I am basically just syncing the following packages:
linux-ck
nvidia-ck
linux-lts

**Comment by artixruby** [comment]
Added:

[goblins]
Include = /etc/pacman.d/mirrorlist
[galaxy-goblins]
Include = /etc/pacman.d/mirrorlist
[gremlins]
Include = /etc/pacman.d/mirrorlist
[galaxy-gremlins]
Include = /etc/pacman.d/mirrorlist

to /etc/pacman.conf

Should beta-testers like myself expect packages to circulate through here often?

**Comment by graysky2** [comment]
So what does this change mean from a practical perspective for updating the kernel and nvidia packages?

**Comment by udeved** [comment]
@artixruby 

I haven't had much time last days, so we are behind schedule.
This may take a bit longer, the jenkins pipeline is not fully tested.

@graysky2 

Not much, but you would be responsible for moving the kernel from testing to stable, or you could do staging a kernel before testing. 
In practical terms, once pipeline is bullet proof, it just means we do not transfer any longer packages via pull request from our testing to stable repos, we follow basically arch procedure, and we drop the separation between system and world git.

**Comment by artixruby** [comment]
That is fine; I look forward to testing this out for you all.

Please remember to eat and sleep @udeved , artoo. The rest of you developers too. We are playing the long game and can afford a few set backs as long as we keep chugging along.

Thank you for all your time and effort devs; береги себя.

**Comment by artixruby** [comment]
[localhost ᒤᕞᕹᓸ]# pacman -S dummy-a dummy-b-bar dummy-b-foo --config=/etc/pacman-artixc.conf --ignore lib32-systemd,geoclue --noconfirm
resolving dependencies...
looking for conflicting packages...

Package (3)           New Version  Net Change  Download Size

gremlins/dummy-a      9999-8         0.00 MiB       0.00 MiB
gremlins/dummy-b-bar  9999-8         0.00 MiB       0.00 MiB
gremlins/dummy-b-foo  9999-8         0.00 MiB       0.00 MiB

Total Download Size:   0.01 MiB
Total Installed Size:  0.01 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 dummy-a-9999-8-x86_64                                               1848.0   B  1805K/s 00:00 [########################################################] 100%
 dummy-b-bar-9999-8-any                                              1844.0   B  0.00B/s 00:00 [########################################################] 100%
 dummy-b-foo-9999-8-any                                              1844.0   B  0.00B/s 00:00 [########################################################] 100%
(3/3) checking keys in keyring                                                                 [########################################################] 100%
(3/3) checking package integrity                                                               [########################################################] 100%
(3/3) loading package files                                                                    [########################################################] 100%
(3/3) checking for file conflicts                                                              [########################################################] 100%
(3/3) checking available disk space                                                            [########################################################] 100%
:: Processing package changes...
(1/3) installing dummy-a                                                                       [########################################################] 100%
(2/3) installing dummy-b-bar                                                                   [########################################################] 100%
(3/3) installing dummy-b-foo                                                                   [########################################################] 100%



The dummy packages install fine. Thumbs up!

**Comment by udeved** [comment]
@graysky2 

https://github.com/artix-linux/pipeline-playground/blob/master/README.md

**Comment by fungilife** [comment]
If you created a dummy pkg with dummy .conf and dummy libraries, like renaming leafpad into testrepos, and place it in goblin and gremlin so we can test the repositories would that help?

And why isn't there a world-gremlin/goblin?  Or will there be one to complete the pattern?

**Comment by udeved** [comment]
@fungilife 

There is nothing the end user can really test with our git repo transition to arch structure.
Testing is more about testing the jenkins pipeline on maintainers end, ie git operations that trigger repo actions on the server.

The won't be a world-remlins, we follow with the move the arch structure, just that testing in arch is gremlins in artix. system and world packages go in gremlins repo, similar to arch's testing with core and extra in it.

**Comment by graysky2** [comment]
@udeved - So where does one obtain `buildtree` and `commitpkg`?

**Comment by udeved** [comment]
@graysky2 

You install 'artools-pkg' from the repos.

As for linux and linux-lts, I automated the sync from arch git to our git, the sync of the kernel builds will also sed ARTIX in for modules. So you can focus on linux-ck.

I haven't updated the readme, the buildtree changed a bit, but buildtree -h will do. buildtree and commitpkg are simple bash scripts.

For your use case, you change linux-ck/trunk.

Then you'd run, assuming you want the linux-ck in testing

    testingpkg -s trunk -p linux-ck -u

If you want to move the kernel from testing to core

    corepkg -s testing -p linux-ck -u

If you clone the repos not using buildtree, run

    git config --bool pull.rebase true

If eg a build failed in testing, you you want to modify the build to fix, run

    commitpkg -s testing -p linux-ck -u

**Comment by graysky2** [comment]
@udeved - Thanks for the info here... I'm just spread too thin these days.  I will need to respectfully bow out of maintaining these for you guys.  I'm sorry.

**Comment by udeved** [comment]
You drop ck maintaining?
If so, I would remove the builds?

**Comment by graysky2** [comment]
@udeved - I would be happy to do with a simple git push but I don't have time to learn a new util that has only one use.

**Comment by udeved** [comment]
@graysky2 

It is basically up to you if you look at two simple helper scripts automating your git operations, or if you don't. But if you don't, you need to manually do the stuff commitpkg does for you, ie git operations.
If you say, its too much to learn for you, I will remove your ck kernel and modules, would be fine too.

In summary, commitpkg takes care of commiting packages, if you do it manually, I would expect flawless commits, eg without pushing again to an already pushed commit. This confuses the jenkins git.
